version: 1.0.{build}
install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force

    Install-Module -Name PSScriptAnalyzer -Force

    Install-Module -Name Pester -Force
build: off
test_script:
- ps: >-
    import-module pester

    $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru

    (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))

    if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}